### ISSUE TITLE
Send all labels and annotations as `extraVars` by default

### ISSUE THREAD

**Issue by jhernand** [openshift/autoheal#39]
Currently the auto heal service can send to the AWX job a set of `extraVars` that are defined as a JSON document:

```yaml
awxJob:
  template: "My template"
  extraVars: |-
    {
      "myvar": "myvalue",
      "yourvar": "yourvalue",
    }
```

This is very useful to send values or labels or annotations of the alert, for example, to send the value of the `instance` label:

```yaml
awxJob:
  template: "My template"
  extraVars: |-
    {
      "instance": "{{ $labels.instance }}",
    }
```

It is so useful that it should be the default: if the `extraVars` field isn't used then we should automatically populate it with all the labels and annotations of the alert. For example, if the alert is like this:

```yaml
labels:
  instance: 192.168.100.7:9100
  job: node-exporter-123
annotations:
  message: "Node '192.168.100.7:9100' is down"
```

Then we should automatically populate the `extraVars` field like this:

```yaml
extraVars: |-
  {
    "labels": {
      "instance": "192.168.100.7:9100",
      "job": "node-exporter-123"
    },
    "annotations": {
      "message": "Node '192.168.100.7
    }
  }
```

Actually we should probably just provide the full alert description:

```yaml
extraVars: |-
  {
    "alerts": [
     ...
    ]
  }
```

This should be compatible with other custom `extraVars` that the user may want to add. For example, the following action:

```yaml
awxJob:
  template: "My template"
  extraVars:
    myvar: myvalue
    yourvalue: yourvalue
```

Should be equivalent to this:

```yaml
awxJob:
  template: "My template"
  extraVars: |-
    {
      "myvar": "myvalue",
      "yourvar": "yourvalue",
      "alerts": [...]
    }
```
