### ISSUE TITLE
Add support for passing the `limit` parameter to AWX jobs

### ISSUE THREAD

**Issue by jhernand** [openshift/autoheal#45]
When an AWX job is started it is possible to pass a `limit` parameter to limit the hosts where it will run. Currently the auto-heal service doesn't support this, but it should allow to pass it. For example, to pass the value of the `instance` label of the alert:

```yaml
awxJob:
  template: "My template"
  extraVars:
    myvar: myvalue
    yourvar: yourvalue
  limit: {{ $labels.instance }}
```

To be able to use that `limit` parameter the job template has to be configured with the _Prompt on launch_ flag, so we should also check that it is set.
