### ISSUE TITLE
Add support for Ansible Runner

### ISSUE THREAD

**Issue by jhernand** [openshift/autoheal#82]
Currently the auto-heal service can react to alerts running AWX jobs or Kubernetes batch jobs. It should also be able to run playbooks using [Ansible Runner](https://github.com/ansible/ansible-runner).

The description of the healing action should contain all the data needed to run the playbook, in an structure similar to the one used by Ansible Runner itself. For example:

```yaml
apiVersion: autoheal.openshift.io/v1alpha2
kind: HealingRule
metadata:
  name: my-rule
labels:
  alertname: "MyAlert"
ansibleRunner:
  env:
    envvars:
      TESTVAR: aval
    extravars:
      ansible_connection: local
      test: val
    passwords:
      "Password:\\s*?$": "some_password"
    settings:
      idle_timeout: 600
      job_timeout: 3600
      pexpect_timeout: 10
    ssh_key: ...
  inventory:
    hosts:
      ...
  project:
    test.yml:
      ...
```

The auto-heal service should take all these information and create a config map (or secret) containing all this information. It should then start a Kubernetes job that runs the Ansible Runner image with the config map (or secret) mounted so that Ansible Runner can use it.

In order to be able to pass passwords and SSH keys to Ansible Runner the auto-heal service should also be able to access Kubernetes secrets, and inject their values into the generated config map. For example, assuming that the SSH private key will be stored in a secret named `mysshkey`, the auto-heal service should support something like this:

```yaml
ssh_key: $secrets.mysshkey['ssh-privatekey']
```
